### ISSUE TITLE
Build against a recent vanilla

### ISSUE THREAD

**Issue by janlimpens** [DingoDjango/DeepOreIdentifier#2]
I tried building this on Linux, but I do not develop in ,net, so it was just too complicated for me to create the necessary tool chain. So it would be a great help, if you could release binaries built against vanilla 1.1.

**Comment by DingoDjango** [comment]
The latest build was for 1.1
https://github.com/DingoDjango/DeepOreIdentifier/releases/tag/v1.1.7364.1

Does it not work for you?

**Comment by janlimpens** [comment]
Ah, sorry, I tried the assembly included in the git repo. Cool, sorry, 
everything working as expected!
Thanks!

Am 17. Mai 2020 7:39:13 vorm. schrieb Dingo <notifications@github.com>:
