### ISSUE TITLE
Restore to Steam Workshop?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [DingoDjango/DeepOreIdentifier#4]
For those of us stuck on v1.1 for various reasons, this was invaluable! I understand not wanting to receive support requests and stuff for a deprecated mod; but perhaps just change the name to "[DEPRECATED 1.1] Deep Ore Identifier" or something like that?

I hope you'll consider restoring this to the workshop! <3

**Comment by DingoDjango** [comment]
It's hidden. Subscribers can still use the mod and all versions are available here on GitHub.

**Comment by ELLIOTTCABLE** [comment]
Yes, I know - that's what I'm saying, is there's no way to subscribe once you've unsubscribed.

Not everybody (read: most people don't) know how to install from GitHub, given that basically everything is on Steam.
